### PR TITLE
Change README to markdown format

### PR DESCRIPTION
**Pull request by gasolin**
for better readability

### CODE REVIEW

**Comment by glandium** [comment]
This was already done in cf6005df92a57125c8a72fea618c254b317240cc

**Comment by gasolin** [comment]
@glandium I don't think cf6005d provide good looking github compatible markdown yet. With this PR the header will be in different case and inline path will be highlighted

**Comment by glandium** [comment]
This is what your README looks like:
https://github.com/glandium/git-cinnabar/tree/f13c88399527b44b1d061c12931e7d92159caa4f

This is what it looks like with cf6005d:
https://github.com/glandium/git-cinnabar/tree/cf6005df92a57125c8a72fea618c254b317240cc

The former isn't being formatted by github.
If you have improvements suggestions for the existing markdown README from cf6005d, please provide a PR against it/master.

**Comment by gasolin** [comment]
Ouch, need rename to `README.md`, will provide correct one soon :p

**Pull request closed without merging**
