### PR TITLE
Support branch names with newlines & carriage-returns.

### PR DESCRIPTION
**Pull request by tloten**

### CODE REVIEW

**Comment by glandium** [comment]
Can you point to a repository that has such branches?

**Comment by glandium** [comment]
At least, with current version of mercurial, it's not possible to create such branches:
```
$ hg branch "$(echo -e "foo\nbar")"
abort: '\n' cannot be used in a name
$ hg branch "$(echo -e "foo\rbar")"
abort: '\r' cannot be used in a name
```

**Comment by glandium** [comment]
https://www.mercurial-scm.org/repo/hg/rev/361ab1e2086f is what added the check to `hg branch`. Interestingly, tags had `\r` and `\n` disallowed before that. The first released version of mercurial with that change is 2.4.

**Comment by glandium** [comment]
Considering how long this has been forbidden, I'd rather not change this for the sake of changing it. I'd rather any change in this function actually do what the TODO items says instead of doing one-offs.

**Comment by tloten** [comment]
That's fair - I thought that may be the case. Feel free to close if you don't want to leave this hanging.
I'm not sure I'll be able to implement the full set any time soon (some of the rules are non-trivial). I did encounter a number of 'funny refname' warnings when cloning so I suspect I will end up coming back to fix properly at some point! Thanks :)

**Comment by glandium** [comment]
If you have addresses of repositories that give you those warnings, that would be useful information... but in an issue, rather than a PR.
I'll close the PR, since in itself, it's not going to achieve much. Any information you can put in a fresh issue would be valuable.

**Pull request closed without merging**
