### PR TITLE
Add a potential reason why roots are being pushed

### PR DESCRIPTION
**Pull request by gregtatum**
I sunk a morning into this, and I figured it would be good to let future Mozillians have a tip on how to fix the issue.

### CODE REVIEW

**Comment by glandium** [comment]
What were you trying to do? Because I feel some failure should happen earlier than that message instead.

**Comment by gregtatum** [comment]
I recently decided to switch back to git from hg (after maybe 3 or 4 years of using hg), but didn't read the inst

Rough steps to reproduce:
* `git clone git@github.com:mozilla/gecko-dev.git --depth=1`
* Create some patches
* `mach try auto`

I could do `moz-phab submit` and was working just fine. However others had some trouble applying the patches I had sent, and I couldn't push to try.

The fix was to do:

`git clone hg::https://hg.mozilla.org/mozilla-unified`

I found out it was shallow cloning off of the wrong repo only after spending a morning trying to figure things out.

**Comment by glandium** [comment]
So you had two problems:
- You were trying to push to a repo while having no local metadata about the mercurial repo. 053e7fcfa8193af149d9ad41f8790c4a1684a3ac now prevents this.
- Your clone was shallow in the first place. 4535ea38af5478d72b4e86918b3032a9278be00e now explicitly rejects shallow commits when pushing.

**Comment by gregtatum** [comment]
Thanks for the extra checks!

**Pull request closed without merging**
