### PR TITLE
Use os.environ inside Git.config on Windows

### LINKED ISSUE #245: os.environb is not available on Windows
https://github.com/glandium/git-cinnabar/blob/e5d2ed6491fa2ecd7775d206006b60d4a4bb59a0/cinnabar/git.py#L137-L140

This causes:

```
Traceback (most recent call last):
  File "c:\Users\Kagami\.mozbuild\git-cinnabar\git-remote-hg", line 22, in <module>
    from cinnabar.githg import GitHgStore
  File "c:\Users\Kagami\.mozbuild\git-cinnabar\cinnabar\githg.py", line 57, in <module>
    from .hg.objects import (
  File "c:\Users\Kagami\.mozbuild\git-cinnabar\cinnabar\hg\objects.py", line 17, in <module>
    if check_enabled('no-mercurial'):
  File "c:\Users\Kagami\.mozbuild\git-cinnabar\cinnabar\util.py", line 116, in __call__
    config = Git.config(self._key) or self._default
  File "c:\Users\Kagami\.mozbuild\git-cinnabar\cinnabar\git.py", line 138, in config
    value = os.environb.get(var)
AttributeError: module 'os' has no attribute 'environb'
```

[Per the documentation](https://docs.python.org/3/library/os.html#os.environb) it's not available on Windows:

>environb is only available if supports_bytes_environ is True.

>True if the native OS type of the environment is bytes (eg. False on Windows).

### PR DESCRIPTION
**Pull request by saschanaz**
Fixes #245

I was already writing a patch before reading your comment 👀

~~This is certainly larger than your patch but I think preferring unicode is more future-proof.~~

Modified to keep using bytes to follow https://github.com/glandium/git-cinnabar/pull/246#issuecomment-613672393

### CODE REVIEW

**Comment by glandium** [comment]
Well, there's a reason why this code was keeping using bytes, and it's because git config has no guaranteed encoding, and this change would break reading non-utf8 configs.

**Comment by saschanaz** [comment]
I guess the CI failure is not my fault 🤔

**Comment by glandium** [comment]
Your clone doesn't seem to have tags or at least the 0.5.4 tag.

**Comment by glandium** [comment]
I cherry-picked the .gitignore change, and fixed the os.environ issue more generally in 1f8252bc037dde24c9b9c51c24cbfd60e336c0a1.

**Pull request closed without merging**
